name: "Build"

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest, macos-14]
              arch: ['amd64']
            fail-fast: false

        name: Build library (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v4
          with:
            global-json-file: global.json

        - name: Build
          run: dotnet build --configuration Release /p:BuildType=Full

        - name: Run tests
          run: dotnet test --configuration Release --verbosity normal --logger GitHubActions /p:BuildType=Full
